// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ityejjciguvaefjmvgwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0eWVqamNpZ3V2YWVmam12Z3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzIwMzksImV4cCI6MjA3NjAwODAzOX0.zVfQNTlTGTRGCWySkj6dkrq2ICk5GuX_by8-tw0yeCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});